using System;
using System.Diagnostics;
using System.IO;

public class RunProcess
{
	/* comment lines generated by ChatGPT 3.5
	In this code:
	The function ShowUserNotes takes two parameters: 
		userNote, which represents the filename of a PDF file, 
		and wrkDir, which is the working directory where the PDF file is located.
	The function first combines the userNote with the wrkDir to create the full path to the PDF file.
	It checks whether the PDF file exists in the specified path using File.Exists. 
	If the file does not exist, it displays a message box with a warning and exits the function early.
	If the PDF file exists, it creates a new process (Process) to open and display the PDF file.
	It sets the FileName property of the process to the userNote (PDF file) and the WorkingDirectory property to wrkDir.
	Finally, it starts the process, which will open the PDF file using the default PDF viewer on the system.
	*/
	private void ShowUserNotes(string userNote, string wrkDir)
	{
		string pdf = wrkDir + "/" + userNote;
		if (!File.Exists(pdf))
		{   MessageBox.Show(this, "No user note was found for the selected script file.");
			return; }
		Process proc = new Process();
		proc.StartInfo.FileName = userNote;
		proc.StartInfo.WorkingDirectory = wrkDir;
		proc.Start();
	}
}